Responsive Menu Button
David-Lanzz/My-Portfolio pull request #7
Opened 2023-01-30 13:39 UTC by David-Lanzz

- We added a responsive menu to display when the hamburger is clicked in the mobile version
- We linked the menu items to their corresponding cards in the HTML page
- We added transitions to the menu button for visual entertainment to the user when clicked

2023-01-30 13:56 UTC, IngDavidTM requested changes
## Hi @David-Lanzz  🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

- [ ] While you did a fantastic job implementing the functionality on your project :1st_place_medal: , as a [project requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md) your project should have commits from you and your parent to make sure that everybody has contributed code on each project. If you don't have a partner, please let the next reviewer know :+1: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-30 13:56 UTC, IngDavidTM commented on styles.css
> +
- [ ] Good job styling your project :100: , but as a project requirement you should stick as much as possible to the Figma template. As you can see below the font size of your elements and the space between them should be bigger :+1: and also the background should be blur.

**Your design**

![Screenshot from 2023-01-30 08-44-56](https://user-images.githubusercontent.com/105117832/215496248-f523ec12-4898-444c-8289-ba9a10a3aa66.png)

**Figma**

![Screenshot from 2023-01-30 08-44-32](https://user-images.githubusercontent.com/105117832/215496407-ab7ee2d0-9d06-4244-b530-887085bcbba9.png)

2023-01-30 13:56 UTC, IngDavidTM commented on script.js
> +const menuButtons = document.querySelectorAll('.menuButton');
- [ ] Kindly don't forget that it is required when the user clicks (or taps) any option of the mobile menu, the mobile menu should disappear, to improve the user experience :+1:

2023-01-31 10:40 UTC, prolajumokeoni approved these changes
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀  
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 16:30 UTC, closed without merging